server:
  port: 8080
  servlet:
    context-path: /hwjob/api/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hwjob_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb://root:root@localhost:27017/hwjob_mongo_db?authSource=admin
      username: root
      password: root
      database: hwjob_mongo_db
      auto-index-creation: true

  messages:
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

initial-app:
  admin:
    username: admin
    password: admin
    name: Admin

api:
  api-province: https://provinces.open-api.vn/api/v2/

cors:
  server-api-ai: http://localhost:5000/
  server-frontend: http://localhost:5173/

jwt:
  signerKey: 21d698ee57633eca2f364129be119e4e237079d8ab664b7a37d2006b92da62d6
  valid-duration: 3600
  refreshable-duration: 604800
  api-key: 0ddfd6ca62a69ea47643e8db5d50d7c09c3155dd92122e35c20a55ad603b8e00

app:
  file:
    storage-dir: hwjob-backend/upload/user-avatar/
    download-prefix: http://localhost:8080/hwjob/api/public/media/
    default-avatar-resource: static/images/default-avatar.png

blockchain:
  ganache-url: http://127.0.0.1:7545
  contract-address: "0x68254d977d6847444CCfe1d6f05f75b3Ea1e9C99"
  private-key: "0xcc9d2a081b003e3d91bf070d9d31b5b025433666e48fd2d415492efb9ae71217"

momo:
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  redirect-url: http://localhost:3000/payment-result
  ipn-url: https://your-backend.com/api/momo/ipn

vnpay:
  tmn-code: V3CCER63
  hash-secret: E6W3C9Q4OAO1H2X8857RIRBHO6BYRTQF
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:5173/payment-result
  ipn-url: https://transpalmar-anaya-banteringly.ngrok-free.dev/hwjob/api/public/vnpay/ipn

# ngrok domain
# ngrok http 8080

